[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "hubspot.crm.obj.lineitems"
version = "2.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Object", "LineItems", "API", "Inventory Management", "E-commerce", "Vendor/HubSpot", "Area/CRM", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.object.lineitems"

[build-options]
observabilityIncluded = true
